site_name: foss-toolchain-mpcnc
pages:
- Home: 'index.md'
- Basics:
  - Freecad part 1: 'freecad_1.md'
  - Controller board, firmware: 'firmware_1.md'
  - ZOOM grbl+RAMPS+auto squaring: 'zoom_1.md'
  - bCNC: 'bcnc_1.md'
  - Milling part 1: 'mill_1.md'
  - Freecad - ramp in, finsish pass, holding tags: 'ext_1.md'
  - Freecad - prepare for 3D: 'freecad_2.md'
- Blender:
  - Motivation: blenderMot.md
  - Installation: blenderInst.md
  - Basic python scripting 4 airfoils: blenderAirfoils.md 
  - KissSlope project: blenderKissSlope.md
- XFLR5:
  - Getting started: xlfr5GettingStarted.md
- Basic aerodynamics:
  - Basic equations: aeroEqn.md
  
theme: readthedocs
#theme: rtd-dropdown

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true


extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  